name: Send AI Predictions

# AI予想を毎朝7時にメール送信するGitHub Actions（←このコメントが認識のコツ！）
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'  # JST 7:00（UTC換算）

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python daily-ai-mail/send_ai_predictions.py
