name: Send AI Predictions Email

on:
  schedule:
    - cron: '0 22 * * *'  # 日本時間7:00はUTCで22:00
  workflow_dispatch:  # 手動実行もできるように

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run prediction mail script
        run: python daily-ai-mail/send_ai_predictions.py

